### ISSUE TITLE
Define a prefix for css and scss files

### ISSUE THREAD

**Issue by rajsite** [AdobeXD/design-system-package-dsp#27]
Is there a way to define a prefix for tokens that are built into css and scss files? Particularly for css and scss files the tokens get applied to the page globally so I would like to use a custom prefix with them.

For example instead of:
```css
:root {
      --black: #000000;
}
```

I'd like to be able to set the prefix `my-prefix` and have the following:
```css
:root {
      --my-prefix-black: #000000;
}
```

I'd also like to conditionally use the prefix. For example, the prefix isn't needed for JS files
